FROM mozilla/phabricator

USER root

RUN \
    apk --update --no-cache add \
        bash \
        g++ \
        git \
        make > /dev/null 2>&1

# Copy arcconfig with loaded extensions
COPY test-arcconfig /app/.arcconfig
